wutsi:
  application:
    server-url: ${wutsi.application.gateway-url}/store
  platform:
    image:
      type: image-kit
      image-kit:
        origin-url: "https://s3.amazonaws.com/int-wutsi"
        endpoint-url: "https://ik.imagekit.io/cx8qxsgz4d"
    storage:
      type: aws
      aws:
        bucket: int-wutsi
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}
