wutsi:
  application:
    server-url: ${wutsi.application.gateway-url}/store
  platform:
    storage:
      type: aws
      aws:
        bucket: prod-wutsi
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}
